const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

const plans = [
  // ─── Free Trial (auto-assigned on signup, not shown as a paid option) ──────
  {
    name: 'Free Trial',
    slug: 'free-trial',
    description: 'Try all Pro features free for 14 days. No card required.',
    planType: 'CRM',
    billingCycle: 'MONTHLY',
    priceInCents: 0,
    currency: 'INR',
    trialDays: 14,
    isActive: true,
    isDefault: true,
    sortOrder: 0,
    maxUsers: 3,
    maxWhatsappSessions: 3,
    maxMessagesPerMonth: 1000,
    maxCampaignsPerMonth: 5,
    trialMaxUsers: null,
    trialMaxWhatsappSessions: null,
    trialMaxMessagesPerMonth: null,
    trialMaxCampaignsPerMonth: null,
    campaignsEnabled: true,
    automationEnabled: true,
    apiEnabled: true,
    softLimitPercent: 80,
    gracePeriodDays: 3,
  },

  // ─── Starter ───────────────────────────────────────────────────
  {
    name: 'Starter',
    slug: 'starter-monthly',
    description: 'Perfect for small sales teams getting started with WhatsApp CRM.',
    planType: 'CRM',
    billingCycle: 'MONTHLY',
    priceInCents: 49900,
    currency: 'INR',
    trialDays: 0,
    isActive: true,
    isDefault: false,
    sortOrder: 1,
    maxUsers: 5,
    maxWhatsappSessions: 5,
    maxMessagesPerMonth: 5000,
    maxCampaignsPerMonth: 10,
    trialMaxUsers: null,
    trialMaxWhatsappSessions: null,
    trialMaxMessagesPerMonth: null,
    trialMaxCampaignsPerMonth: null,
    campaignsEnabled: true,
    automationEnabled: false,
    apiEnabled: false,
    softLimitPercent: 80,
    gracePeriodDays: 3,
  },
  {
    name: 'Starter',
    slug: 'starter-yearly',
    description: 'Perfect for small sales teams getting started with WhatsApp CRM.',
    planType: 'CRM',
    billingCycle: 'YEARLY',
    priceInCents: 499000,
    currency: 'INR',
    trialDays: 0,
    isActive: true,
    isDefault: false,
    sortOrder: 2,
    maxUsers: 5,
    maxWhatsappSessions: 5,
    maxMessagesPerMonth: 5000,
    maxCampaignsPerMonth: 10,
    trialMaxUsers: null,
    trialMaxWhatsappSessions: null,
    trialMaxMessagesPerMonth: null,
    trialMaxCampaignsPerMonth: null,
    campaignsEnabled: true,
    automationEnabled: false,
    apiEnabled: false,
    softLimitPercent: 80,
    gracePeriodDays: 3,
  },

  // ─── Growth ────────────────────────────────────────────────────
  {
    name: 'Growth',
    slug: 'growth-monthly',
    description: 'For growing teams that need automation and more capacity.',
    planType: 'CRM',
    billingCycle: 'MONTHLY',
    priceInCents: 99900,
    currency: 'INR',
    trialDays: 0,
    isActive: true,
    isDefault: false,
    sortOrder: 3,
    maxUsers: 15,
    maxWhatsappSessions: 15,
    maxMessagesPerMonth: 25000,
    maxCampaignsPerMonth: 50,
    trialMaxUsers: null,
    trialMaxWhatsappSessions: null,
    trialMaxMessagesPerMonth: null,
    trialMaxCampaignsPerMonth: null,
    campaignsEnabled: true,
    automationEnabled: true,
    apiEnabled: false,
    softLimitPercent: 80,
    gracePeriodDays: 3,
  },
  {
    name: 'Growth',
    slug: 'growth-yearly',
    description: 'For growing teams that need automation and more capacity.',
    planType: 'CRM',
    billingCycle: 'YEARLY',
    priceInCents: 999000,
    currency: 'INR',
    trialDays: 0,
    isActive: true,
    isDefault: false,
    sortOrder: 4,
    maxUsers: 15,
    maxWhatsappSessions: 15,
    maxMessagesPerMonth: 25000,
    maxCampaignsPerMonth: 50,
    trialMaxUsers: null,
    trialMaxWhatsappSessions: null,
    trialMaxMessagesPerMonth: null,
    trialMaxCampaignsPerMonth: null,
    campaignsEnabled: true,
    automationEnabled: true,
    apiEnabled: false,
    softLimitPercent: 80,
    gracePeriodDays: 3,
  },

  // ─── Pro ───────────────────────────────────────────────────────
  {
    name: 'Pro',
    slug: 'pro-monthly',
    description: 'Full-featured plan with API access for mid-size businesses.',
    planType: 'CRM',
    billingCycle: 'MONTHLY',
    priceInCents: 199900,
    currency: 'INR',
    trialDays: 0,
    isActive: true,
    isDefault: false,
    sortOrder: 5,
    maxUsers: 50,
    maxWhatsappSessions: 50,
    maxMessagesPerMonth: 100000,
    maxCampaignsPerMonth: 200,
    campaignsEnabled: true,
    automationEnabled: true,
    apiEnabled: true,
    softLimitPercent: 80,
    gracePeriodDays: 3,
  },
  {
    name: 'Pro',
    slug: 'pro-yearly',
    description: 'Full-featured plan with API access for mid-size businesses.',
    planType: 'CRM',
    billingCycle: 'YEARLY',
    priceInCents: 1999000,
    currency: 'INR',
    trialDays: 0,
    isActive: true,
    isDefault: false,
    sortOrder: 6,
    maxUsers: 50,
    maxWhatsappSessions: 50,
    maxMessagesPerMonth: 100000,
    maxCampaignsPerMonth: 200,
    campaignsEnabled: true,
    automationEnabled: true,
    apiEnabled: true,
    softLimitPercent: 80,
    gracePeriodDays: 3,
  },

  // ─── Enterprise ────────────────────────────────────────────────
  {
    name: 'Enterprise',
    slug: 'enterprise-monthly',
    description: 'Unlimited scale for large teams. Contact us for a custom quote.',
    planType: 'CRM',
    billingCycle: 'MONTHLY',
    priceInCents: 399900,
    currency: 'INR',
    trialDays: 0,
    isActive: true,
    isDefault: false,
    sortOrder: 7,
    maxUsers: 200,
    maxWhatsappSessions: 200,
    maxMessagesPerMonth: 0,
    maxCampaignsPerMonth: 0,
    campaignsEnabled: true,
    automationEnabled: true,
    apiEnabled: true,
    softLimitPercent: 80,
    gracePeriodDays: 7,
  },
  {
    name: 'Enterprise',
    slug: 'enterprise-yearly',
    description: 'Unlimited scale for large teams. Contact us for a custom quote.',
    planType: 'CRM',
    billingCycle: 'YEARLY',
    priceInCents: 3999000,
    currency: 'INR',
    trialDays: 0,
    isActive: true,
    isDefault: false,
    sortOrder: 8,
    maxUsers: 200,
    maxWhatsappSessions: 200,
    maxMessagesPerMonth: 0,
    maxCampaignsPerMonth: 0,
    campaignsEnabled: true,
    automationEnabled: true,
    apiEnabled: true,
    softLimitPercent: 80,
    gracePeriodDays: 7,
  },
];

async function main() {
  console.log('Seeding billing plans...');

  for (const plan of plans) {
    const result = await p.plan.upsert({
      where: {
        unique_plan_version: {
          slug: plan.slug,
          billingCycle: plan.billingCycle,
          version: 1,
        },
      },
      update: {
        name: plan.name,
        description: plan.description,
        priceInCents: plan.priceInCents,
        trialDays: plan.trialDays,
        isActive: plan.isActive,
        isDefault: plan.isDefault,
        sortOrder: plan.sortOrder,
        maxUsers: plan.maxUsers,
        maxWhatsappSessions: plan.maxWhatsappSessions,
        maxMessagesPerMonth: plan.maxMessagesPerMonth,
        maxCampaignsPerMonth: plan.maxCampaignsPerMonth,
        trialMaxUsers: plan.trialMaxUsers ?? null,
        trialMaxWhatsappSessions: plan.trialMaxWhatsappSessions ?? null,
        trialMaxMessagesPerMonth: plan.trialMaxMessagesPerMonth ?? null,
        trialMaxCampaignsPerMonth: plan.trialMaxCampaignsPerMonth ?? null,
        campaignsEnabled: plan.campaignsEnabled,
        automationEnabled: plan.automationEnabled,
        apiEnabled: plan.apiEnabled,
        softLimitPercent: plan.softLimitPercent,
        gracePeriodDays: plan.gracePeriodDays,
      },
      create: plan,
    });
    console.log(`  ✓ ${result.name} (${result.billingCycle}) — ₹${result.priceInCents / 100}/mo [${result.slug}]`);
  }

  console.log(`\nDone! Seeded ${plans.length} plans.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => p.$disconnect());
